[package]
name = "tag"
version = "1.0.0"
edition = "2021"

[dependencies]
strum = "^0.26"
strum_macros = "^0.26"
serde_json = "1.0.107"
serde = { version = "1.0.188", features = ["derive"] }
home = "^0.5"
